routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', 'HomeController@index');
Route::get('/home', 'HomeController@index')->name('home');

Route::group(['middleware' => ['auth']], function () {
    Route::resource('accounts', 'AccountController');

    Route::resource('segments', 'SegmentController');
    Route::get('/segments/{id}/matched', 'SegmentController@matched')->name('segments.matched');

    Route::resource('mailing_lists', 'MailingListController');
    Route::get('/mailing_lists/{id}/process', 'JobController@processQueue')->name('mailing_lists.process');

    Route::get('/jobs', 'JobController@index')->name('jobs.index');
    Route::get('/jobs/{id}', 'JobController@show')->name('jobs.show');
    Route::get('/jobs/{id}/status', 'JobController@checkStatus')->name('jobs.status');
    Route::get('/test', 'JobController@test')->name('jobs.status');
});

app/Account.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Account extends Model
{
    protected $fillable = [
        'email',
        'gender',
        'age',
        'email',
    //        'city',
        'country_id',
    //        'job_title'
    ];

    /**
     * Get Accounts Country
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function country()
    {
        return $this->belongsTo('App\Country');
    }
}

app/Http/Controllers/AccountController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Country;
use App\Account;

class AccountController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $accounts = Account::with('country')->orderBy('id', 'desc')->paginate(50);
        return view('accounts.index', compact('accounts'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $countries = Country::pluck('name', 'id');
        return view('accounts.create', compact('countries'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request Request received
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate(
            [
            'email'=>'bail|required|email|unique:accounts',
            'age'=>'required',
            'gender'=>'required',
            'country_id'=>'required',
            ]
        );

        $account = new Account(
            [
            'email' => $request->get('email'),
            'age' => $request->get('age'),
            'gender' => $request->get('gender'),
            'country_id' => $request->get('country_id')
            ]
        );
        $account->save();
        return redirect('/accounts')->with('success', 'account saved!');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id Account id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $account = Account::findOrFail($id);
        $countries = Country::pluck('name', 'id');
        return view('accounts.edit', compact('account', 'countries'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request Request received
     * @param  int                      $id      Account id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate(
            [
            'email'=>'required',
            'age'=>'required',
            'gender'=>'required',
            'country_id'=>'required',
            ]
        );


        $account = Account::findOrFail($id);
        $account->email = $request->get('email');
        $account->age = $request->get('age');
        $account->gender = $request->get('gender');
        $account->country_id = $request->get('country_id');
        $account->save();

        return redirect('/accounts')->with('success', 'Account updated!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id Account id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $account = account::findOrFail($id);
        $account->delete();

        return redirect('/accounts')->with('success', 'Account deleted!');
    }
}

resources/views/accounts/create.blade.php
@extends('layouts.app')

@section('title', 'Add Account')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="row">
                <div class="col-sm-auto offset-sm-1">
                    <h1 class="display-3">Add a account</h1>
                    <div>
                        @if ($errors->any())
                            <div class="alert alert-danger">
                                <ul>
                                    @foreach ($errors->all() as $error)
                                        <li>{{ $error }}</li>
                                    @endforeach
                                </ul>
                            </div><br />
                        @endif
                        {{ Form::open(['url' => route('accounts.store')]) }}
                            @csrf
                            <div class="form-group">
                                {{ Form::label('email', 'Email:') }}
                                {{ Form::email('email', null, ['class' => 'form-control']) }}
                            </div>

                            <div class="form-group">
                                {{ Form::label('age', 'Age:') }}
                                {{ Form::number('age', null, ['class' => 'form-control']) }}
                            </div>

                            <div class="form-group">
                                {{ Form::label('gender', 'Male') }}
                                {{ Form::radio('gender', 'Male') }}
                                {{ Form::label('gender', 'Female') }}
                                {{ Form::radio('gender', 'Female') }}
                            </div>

                            <div class="form-group">
                                {{ Form::label('country_id', 'Country:') }}
                                {{ Form::select('country_id', $countries, null, ['class' => 'form-control', 'placeholder' => 'Select Country']) }}
                            </div>
                            <a href="{{ route('accounts.index') }}" class="btn btn-primary-outline btn-link">Cancel</a>
                            <button type="submit" class="btn btn-primary-outline">Add account</button>
                        {{ Form::close() }}
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/accounts/edit.blade.php
@extends('layouts.app')

@section('title', 'Edit Account')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="row">
                <div class="col-sm-auto offset-sm-1">
                    <h1 class="display-3">Edit a account</h1>
                    <div>
                        @if ($errors->any())
                            <div class="alert alert-danger">
                                <ul>
                                    @foreach ($errors->all() as $error)
                                        <li>{{ $error }}</li>
                                    @endforeach
                                </ul>
                            </div><br />
                        @endif
                        {{ Form::open(['url' => route('accounts.update', $account->id), 'method' => 'put']) }}
                        @csrf
                        <div class="form-group">
                            {{ Form::label('email', 'Email:') }}
                            {{ Form::email('email', $account->email, ['class' => 'form-control']) }}
                        </div>

                        <div class="form-group">
                            {{ Form::label('age', 'Age:') }}
                            {{ Form::number('age', $account->age, ['class' => 'form-control']) }}
                        </div>

                        <div class="form-group">
                            {{ Form::label('gender', 'Male') }}
                            {{ Form::radio('gender', 'Male', $account->gender == 'Male') }}
                            {{ Form::label('gender', 'Female') }}
                            {{ Form::radio('gender', 'Female', $account->gender == 'Female') }}
                        </div>

                        <div class="form-group">
                            {{ Form::label('country_id', 'Country:') }}
                            {{ Form::select('country_id', $countries, $account->country_id, ['class' => 'form-control', 'placeholder' => 'Select Country']) }}
                        </div>
                        <a href="{{ route('accounts.index') }}" class="btn btn-primary-outline btn-link">Cancel</a>
                        <button type="submit" class="btn btn-primary-outline">Update account</button>
                        {{ Form::close() }}
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/accounts/index.blade.php
@extends('layouts.app')
@section('title', 'Accounts')
@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-sm-12">
                @if(session()->get('success'))
                    <div class="alert alert-success">
                        {{ session()->get('success') }}
                    </div>
                @endif
                <h1 class="display-3">Accounts</h1>
                <a href="{{ route('accounts.create') }}" class="btn btn-primary-outline btn-link float-right">Add account</a>
                <table class="table table-striped">
                    <thead>
                    <tr>
                        <td>ID</td>
                        <td>Email</td>
                        <td>Age</td>
                        <td>Gender</td>
                        <td>Country</td>
                        <td colspan = 2>Actions</td>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach($accounts as $account)
                        <tr>
                            <td>{{$account->id}}</td>
                            <td>{{$account->email}}</td>
                            <td>{{$account->age}}</td>
                            <td>{{$account->gender}}</td>
                            <td>{{$account->country->name}}</td>
                            <td>
                                <a href="{{ route('accounts.edit',$account->id)}}" class="btn btn-primary">Edit</a>
                            </td>
                            <td>
                                <form action="{{ route('accounts.destroy', $account->id)}}" method="post">
                                    @csrf
                                    @method('DELETE')
                                    <button class="btn btn-danger" type="submit">Delete</button>
                                </form>
                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
                {{ $accounts->links() }}
            </div>
        <div>
    </div>
@endsection