routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', 'HomeController@index');
Route::get('/home', 'HomeController@index')->name('home');

Route::group(['middleware' => ['auth']], function () {
    Route::resource('accounts', 'AccountController');

    Route::resource('segments', 'SegmentController');
    Route::get('/segments/{id}/matched', 'SegmentController@matched')->name('segments.matched');

    Route::resource('mailing_lists', 'MailingListController');
    Route::get('/mailing_lists/{id}/process', 'JobController@processQueue')->name('mailing_lists.process');

    Route::get('/jobs', 'JobController@index')->name('jobs.index');
    Route::get('/jobs/{id}', 'JobController@show')->name('jobs.show');
    Route::get('/jobs/{id}/status', 'JobController@checkStatus')->name('jobs.status');
    Route::get('/test', 'JobController@test')->name('jobs.status');
});

app/MailingList.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class MailingList extends Model
{
    protected $fillable = [
        'name',
        'segment_id',
        'processed',
        'template'
    ];

    /**
     * Get the Mailing lists segment.
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function segment()
    {
        return $this->belongsTo('App\Segment');
    }
}

app/Http/Controllers/MailingListController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Account;
use App\Country;
use App\Segment;
use App\MailingList;

class MailingListController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $mailing_lists = MailingList::with('segment')
            ->orderBy('id', 'desc')
            ->paginate(20);
        return view('mailing_lists.index', compact('mailing_lists'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $segments = Segment::pluck('name', 'id');
        return view('mailing_lists.create', compact('segments'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request Request received
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate(
            [
            'name'=>'required',
            'segment_id'=>'required|exists:segments,id',
            'template'=>'required',
            ]
        );

        $mailing_list = new MailingList(
            [
            'name' => $request->get('name'),
            'segment_id' => $request->get('segment_id'),
            'template' => $request->get('template')
            ]
        );
        $mailing_list->save();
        return redirect('/mailing_lists')->with('success', 'Mailing list saved!');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id Mailing list id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $mailing_list = MailingList::findOrFail($id);
        $segments = Segment::pluck('name', 'id');
        return view('mailing_lists.edit', compact('segments', 'mailing_list'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request Request received
     * @param  int                      $id      Mailing list id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate(
            [
            'name'=>'required',
            'segment_id'=>'required|exists:segments,id',
            'template'=>'required',
            ]
        );

        $mailing_list = MailingList::findOrFail($id);
        $mailing_list->name = $request->get('name');
        $mailing_list->segment_id = $request->get('segment_id');
        $mailing_list->template = $request->get('template');
        $mailing_list->save();

        return redirect('/mailing_lists')->with('success', 'Mailing List updated!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id Mailing List id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $mailing_list = MailingList::findOrFail($id);
        $mailing_list->delete();

        return redirect('/mailing_lists')->with('success', 'Segment deleted!');
    }
}

resources/views/mailing_lists/create.blade.php
@extends('layouts.app')

@section('title', 'Add Mailing List')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="row">
                <div class="col-sm-auto offset-sm-1">
                    <h1 class="display-3">Add Mailing List</h1>
                    <div>
                        @if ($errors->any())
                            <div class="alert alert-danger">
                                <ul>
                                    @foreach ($errors->all() as $error)
                                        <li>{{ $error }}</li>
                                    @endforeach
                                </ul>
                            </div><br />
                        @endif
                        {{ Form::open(['url' => route('mailing_lists.store')]) }}
                            @csrf
                            <div class="form-group">
                                {{ Form::label('name', 'Name:') }}
                                {{ Form::text('name', null, ['class' => 'form-control']) }}
                            </div>

                            <div class="form-group">
                                {{ Form::label('template', 'Template:') }}
                                {{ Form::textarea('template', null, ['class' => 'form-control']) }}
                            </div>

                            <div class="form-group">
                                {{ Form::label('segment_id', 'Segment:') }}
                                {{ Form::select('segment_id', $segments, null, ['class' => 'form-control', 'placeholder' => 'Select Segment']) }}
                            </div>
                            <a href="{{ route('mailing_lists.index') }}" class="btn btn-primary-outline btn-link">Cancel</a>
                            <button type="submit" class="btn btn-primary-outline">Add mailing list</button>
                        {{ Form::close() }}
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/mailing_lists/edit.blade.php
@extends('layouts.app')

@section('title', 'Edit Mailing List')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="row">
                <div class="col-sm-auto offset-sm-1">
                    <h1 class="display-3">Edit a Mailing List</h1>
                    <div>
                        @if ($errors->any())
                            <div class="alert alert-danger">
                                <ul>
                                    @foreach ($errors->all() as $error)
                                        <li>{{ $error }}</li>
                                    @endforeach
                                </ul>
                            </div><br />
                        @endif
                        {{ Form::open(['url' => route('mailing_lists.update', $mailing_list->id), 'method' => 'put']) }}
                            @csrf
                            <div class="form-group">
                                {{ Form::label('name', 'Name:') }}
                                {{ Form::text('name', $mailing_list->name, ['class' => 'form-control']) }}
                            </div>

                            <div class="form-group">
                                {{ Form::label('template', 'Template:') }}
                                {{ Form::textarea('template', $mailing_list->template, ['class' => 'form-control']) }}
                            </div>

                            <div class="form-group">
                                {{ Form::label('segment_id', 'Segment:') }}
                                {{ Form::select('segment_id', $segments, $mailing_list->segment_id, ['class' => 'form-control', 'placeholder' => 'Select Segment']) }}
                            </div>
                            <a href="{{ route('mailing_lists.index') }}" class="btn btn-primary-outline btn-link">Cancel</a>
                            <button type="submit" class="btn btn-primary-outline">Update Mailing List</button>
                        {{ Form::close() }}
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/mailing_lists/index.blade.php
@extends('layouts.app')
@section('title', 'Mailing lists')
@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-sm-12">
                @if(session()->get('success'))
                    <div class="alert alert-success">
                        {{ session()->get('success') }}
                    </div>
                @endif
                <h1 class="display-3">Mailing lists</h1>
                <a href="{{ route('mailing_lists.create') }}" class="btn btn-primary-outline btn-link float-right">Add Mailing List</a>
                <table class="table table-striped">
                    <thead>
                    <tr>
                        <td>ID</td>
                        <td>Name</td>
                        <td>Segment</td>
                        <td>Processed</td>
                        <td colspan=3>Actions</td>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach($mailing_lists as $mailing_list)
                        <tr>
                            <td>{{$mailing_list->id}}</td>
                            <td>{{$mailing_list->name}}</td>
                            <td>{{($mailing_list->segment) ? $mailing_list->segment->name : ''}}</td>
                            <td>{{$mailing_list->processed}}</td>
                            <td>
                                <a href="{{ route('mailing_lists.edit',$mailing_list->id)}}" class="btn btn-primary">Edit</a>
                            </td>
                            <td>
                                <a href="{{ route('mailing_lists.process',$mailing_list->id)}}" class="btn btn-primary">Add Job for sending emails</a>
                            </td>
                            <td>
                                <form action="{{ route('mailing_lists.destroy', $mailing_list->id)}}" method="post">
                                    @csrf
                                    @method('DELETE')
                                    <button class="btn btn-danger" type="submit">Delete</button>
                                </form>
                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
                {{ $mailing_lists->links() }}
            </div>
        <div>
    </div>
@endsection