routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', 'HomeController@index');
Route::get('/home', 'HomeController@index')->name('home');

Route::group(['middleware' => ['auth']], function () {
    Route::resource('accounts', 'AccountController');

    Route::resource('segments', 'SegmentController');
    Route::get('/segments/{id}/matched', 'SegmentController@matched')->name('segments.matched');

    Route::resource('mailing_lists', 'MailingListController');
    Route::get('/mailing_lists/{id}/process', 'JobController@processQueue')->name('mailing_lists.process');

    Route::get('/jobs', 'JobController@index')->name('jobs.index');
    Route::get('/jobs/{id}', 'JobController@show')->name('jobs.show');
    Route::get('/jobs/{id}/status', 'JobController@checkStatus')->name('jobs.status');
    Route::get('/test', 'JobController@test')->name('jobs.status');
});

app/Segment.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Segment extends Model
{
    protected $fillable = [
        'name',
        'gender',
        'from_age',
        'to_age',
        'country_id',
    ];

    /**
     * Get Segment country
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function country()
    {
        return $this->belongsTo('App\Country');
    }
}

app/Http/Controllers/SegmentController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Account;
use App\Country;
use App\Segment;

class SegmentController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $segments = Segment::with('country')->orderBy('id', 'desc')->paginate(50);
        return view('segments.index', compact('segments'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $countries = Country::pluck('name', 'id');
        return view('segments.create', compact('countries'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request Request received
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $messages = [
            'gt' => 'Ages to must be grater than Ages from',
        ];
        $request->validate(
            [
            'name'=>'required',
            'from_age'=>'nullable|integer|max:100|min:10',
            'to_age'=>'nullable|gt:from_age|integer|max:100|min:10',
            'gender'=>'nullable|in:Male,Female',
            'country_id'=>'nullable|exists:countries,id',
            ], $messages
        );

        $segment = new Segment(
            [
            'name' => $request->get('name'),
            'from_age' => ($request->get('from_age'))?$request->get('from_age'):null,
            'to_age' => ($request->get('to_age'))?$request->get('to_age'):null,
            'gender' => ($request->get('gender'))?$request->get('gender'):null,
            'country_id' => ($request->get('country_id'))?$request->get('country_id'):null
            ]
        );
        $segment->save();
        return redirect('/segments')->with('success', 'segment saved!');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id Segment id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $segment = Segment::findOrFail($id);
        $countries = Country::pluck('name', 'id');
        return view('segments.edit', compact('segment', 'countries'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request Request received
     * @param  int                      $id      Segment id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $messages = [
            'gt' => 'Ages to must be grater than Ages from',
        ];
        $request->validate(
            [
            'name'=>'required',
            'from_age'=>'present|integer|max:100|min:10',
            'to_age'=>'present|gt:from_age|integer|max:100|min:10',
            'gender'=>'nullable|in:Male,Female',
            'country_id'=>'present|exists:countries,id',
            ], $messages
        );


        $segment = Segment::findOrFail($id);
        $segment->name = $request->get('name');
        $segment->from_age = ($request->get('from_age'))?$request->get('from_age'):null;
        $segment->to_age = ($request->get('to_age'))?$request->get('to_age'):null;
        $segment->gender = ($request->get('gender'))?$request->get('gender'):null;
        $segment->country_id = ($request->get('country_id'))?$request->get('country_id'):null;
        $segment->save();

        return redirect('/segments')->with('success', 'segment updated!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id Segment id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $segment = Segment::findOrFail($id);
        $segment->delete();

        return redirect('/segments')->with('success', 'Segment deleted!');
    }

    /**
     * List of accounts that matched for segment.
     *
     * @param  int $id Segment id
     * @return \Illuminate\Http\Response
     */
    public function matched($id)
    {
        $segment = Segment::findOrFail($id);
        $accounts = Account::with('country')
        ->when(
            $segment->gender, function ($query) use ($segment) {
                $query->where('gender', '=', $segment->gender);
            }
        )
        ->when(
            $segment->from_age, function ($query) use ($segment) {
                $query->where('age', '>', $segment->from_age);
            }
        )
        ->when(
            $segment->to_age, function ($query) use ($segment) {
                $query->where('age', '<', $segment->to_age);
            }
        )
        ->when(
            $segment->country_id, function ($query) use ($segment) {
                $query->where('country_id', '=', $segment->country_id);
            }
        )
        ->paginate(20);

        return view('segments.matched', compact('segment', 'accounts'));
    }
}

resources/views/segments/create.blade.php
@extends('layouts.app')

@section('title', 'Add Segment')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="row">
                <div class="col-sm-auto offset-sm-1">
                    <h1 class="display-3">Add a segment</h1>
                    <div>
                        @if ($errors->any())
                            <div class="alert alert-danger">
                                <ul>
                                    @foreach ($errors->all() as $error)
                                        <li>{{ $error }}</li>
                                    @endforeach
                                </ul>
                            </div><br />
                        @endif
                        {{ Form::open(['url' => route('segments.store')]) }}
                            @csrf
                            <div class="form-group">
                                {{ Form::label('name', 'Name:') }}
                                {{ Form::text('name', null, ['class' => 'form-control']) }}
                            </div>

                            <div class="form-group">
                                {{ Form::label('from_age', 'Ages from:') }}
                                {{ Form::number('from_age', null, ['class' => 'form-control']) }}
                            </div>
                            <div class="form-group">
                                {{ Form::label('to_age', 'Ages before:') }}
                                {{ Form::number('to_age', null, ['class' => 'form-control']) }}
                            </div>

                            <div class="form-group">
                                {{ Form::label('gender', 'Male') }}
                                {{ Form::radio('gender', 'Male') }}
                                {{ Form::label('gender', 'Female') }}
                                {{ Form::radio('gender', 'Female') }}
                            </div>

                            <div class="form-group">
                                {{ Form::label('country_id', 'Country:') }}
                                {{ Form::select('country_id', $countries, null, ['class' => 'form-control', 'placeholder' => 'Select Country']) }}
                            </div>
                            <a href="{{ route('segments.index') }}" class="btn btn-primary-outline btn-link">Cancel</a>
                            <button type="submit" class="btn btn-primary-outline">Add segment</button>
                        {{ Form::close() }}
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/segments/edit.blade.php
@extends('layouts.app')

@section('title', 'Edit Segment')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="row">
                <div class="col-sm-auto offset-sm-1">
                    <h1 class="display-3">Edit a segment</h1>
                    <div>
                        @if ($errors->any())
                            <div class="alert alert-danger">
                                <ul>
                                    @foreach ($errors->all() as $error)
                                        <li>{{ $error }}</li>
                                    @endforeach
                                </ul>
                            </div><br />
                        @endif
                        {{ Form::open(['url' => route('segments.update', $segment->id), 'method' => 'put']) }}
                        @csrf
                        <div class="form-group">
                            {{ Form::label('name', 'Name:') }}
                            {{ Form::text('name', $segment->name, ['class' => 'form-control']) }}
                        </div>

                        <div class="form-group">
                            {{ Form::label('from_age', 'Ages from:') }}
                            {{ Form::number('from_age', $segment->from_age, ['class' => 'form-control']) }}
                        </div>
                        <div class="form-group">
                            {{ Form::label('to_age', 'Ages before:') }}
                            {{ Form::number('to_age', $segment->to_age, ['class' => 'form-control']) }}
                        </div>

                        <div class="form-group">
                            {{ Form::label('gender', 'Male') }}
                            {{ Form::radio('gender', 'Male', $segment->gender == 'Male') }}
                            {{ Form::label('gender', 'Female') }}
                            {{ Form::radio('gender', 'Female', $segment->gender == 'Female') }}
                        </div>

                        <div class="form-group">
                            {{ Form::label('country_id', 'Country:') }}
                            {{ Form::select('country_id', $countries, $segment->country_id, ['class' => 'form-control', 'placeholder' => 'Select Country']) }}
                        </div>
                        <a href="{{ route('segments.index') }}" class="btn btn-primary-outline btn-link">Cancel</a>
                        <button type="submit" class="btn btn-primary-outline">Update segment</button>
                        {{ Form::close() }}
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/segments/index.blade.php
@extends('layouts.app')
@section('title', 'Segments')
@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-sm-12">
                @if(session()->get('success'))
                    <div class="alert alert-success">
                        {{ session()->get('success') }}
                    </div>
                @endif
                <h1 class="display-3">Segments</h1>
                <a href="{{ route('segments.create') }}" class="btn btn-primary-outline btn-link float-right">Add Segment</a>
                <table class="table table-striped">
                    <thead>
                    <tr>
                        <td>ID</td>
                        <td>Name</td>
                        <td>Age</td>
                        <td>Gender</td>
                        <td>Country</td>
                        <td colspan = 4>Actions</td>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach($segments as $segment)
                        <tr>
                            <td>{{$segment->id}}</td>
                            <td>{{$segment->name}}</td>
                            <td>{{$segment->from_age . ' - ' . $segment->to_age}}</td>
                            <td>{{$segment->gender}}</td>
                            <td>{{($segment->country) ? $segment->country->name : ''}}</td>
                            <td>
                                <a href="{{ route('segments.edit',$segment->id)}}" class="btn btn-primary">Edit</a>
                            </td>
                            <td>
                                <a href="{{ route('segments.matched',$segment->id)}}" class="btn btn-primary">View Matched</a>
                            </td>
                            <td>
                                <form action="{{ route('segments.destroy', $segment->id)}}" method="post">
                                    @csrf
                                    @method('DELETE')
                                    <button class="btn btn-danger" type="submit">Delete</button>
                                </form>
                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
                {{ $segments->links() }}
            </div>
        <div>
    </div>
@endsection

resources/views/segments/matched.blade.php
@extends('layouts.app')
@section('title', 'Accounts')
@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-sm-12">
                @if(session()->get('success'))
                    <div class="alert alert-success">
                        {{ session()->get('success') }}
                    </div>
                @endif
                <h1 class="display-3">Matched Accounts for {{ $segment->name }}</h1>
                <ul>
                    <li>Gender : {{ $segment->gender }}</li>
                    <li>Age : {{ $segment->from_age . '-' . $segment->to_age }}</li>
                    <li>Country : {{($segment->country) ? $segment->country->name : ''}}</li>
                    <li>Total number of matched accounts: {{$accounts->total()}}</li>

                </ul>
                <table class="table table-striped">
                    <thead>
                    <tr>
                        <td>ID</td>
                        <td>Email</td>
                        <td>Age</td>
                        <td>Gender</td>
                        <td>Country</td>
                        <td colspan = 2>Actions</td>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach($accounts as $account)
                        <tr>
                            <td>{{$account->id}}</td>
                            <td>{{$account->email}}</td>
                            <td>{{$account->age}}</td>
                            <td>{{$account->gender}}</td>
                            <td>{{$account->country->name}}</td>
                            <td>
                                <a href="{{ route('accounts.edit',$account->id)}}" class="btn btn-primary">Edit</a>
                            </td>
                            <td>
                                <form action="{{ route('accounts.destroy', $account->id)}}" method="post">
                                    @csrf
                                    @method('DELETE')
                                    <button class="btn btn-danger" type="submit">Delete</button>
                                </form>
                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
                {{ $accounts->links() }}
            </div>
        <div>
    </div>
@endsection